### ISSUE TITLE
Wrong handling of repeated packed scalar fields

### ISSUE THREAD

**Issue by denizzzka** [dcarp/protobuf-d#22]
Repeated packed scalar fields like this:
```
repeated sint64 id = 1 [packed = true];
```

Readed with error:
google.protobuf.common.ProtobufException@../protobuf-d/src/google/protobuf/decoding.d(188): Wrong wire format 'withLength' of field DenseNodes.id, expected 'varint'

This field must be threated as wire format 'withLength':
https://developers.google.com/protocol-buffers/docs/encoding

> Packed Repeated Fields
> Version 2.1.0 introduced packed repeated fields, which in proto2 are declared like repeated fields but with the special [packed=true] option. In proto3, repeated fields of scalar numeric types are packed by default. These function like repeated fields, but are encoded differently. A packed repeated field containing zero elements does not appear in the encoded message. Otherwise, all of the elements of the field are packed into a single key-value pair with wire type 2 (length-delimited). Each element is encoded the same way it would be normally, except without a key preceding it.

**Comment by dcarp** [comment]
Are you sure? I just added some [unittests](https://github.com/dcarp/protobuf-d/commit/4c62fb741b60b39f834320d6ab8432c245020848) and it seams to work.

Can you provide the generated D code for the `id` field?

**Comment by denizzzka** [comment]
> I just added some unittests and it seams to work.

Looks like it creates and then tests created binary by same potentially buggy function.

It is neeed to run test on some test blob created by third-side software.

**Comment by denizzzka** [comment]
> Can you provide the generated D code for the id field?

```D
@Proto(1, Wire.zigzag) long[] id = protoDefaultValue!(long[]);
```

**Comment by dcarp** [comment]
The generated code is wrong. It should be
``` d
@Proto(1, Wire.zigzag, Yes.packed) long[] id = protoDefaultValue!(long[]);
```

**Comment by denizzzka** [comment]
Yes, right.

I tried with protoc version 3.8.0 and 3.6.* with same result.

**Comment by dcarp** [comment]
Thanks, I'll add a test for protoc plugin as well, and eventually fix the bug there.

**Comment by denizzzka** [comment]
New version is works fine! Thanks!
