### ISSUE TITLE
Provide Dub Example of Build Configuration

### ISSUE THREAD

**Issue by vnayar** [dcarp/protobuf-d#24]
Adding an example that builds a library from the D code that was generated by the `protoc` compiler could help with a common use case for users of this library.

The use case is a project with a server and client component that may share via a library the D code generated by this tool.  In a project I am working on that does this, I am currently using the following Dub configuration:

```sdl
////
// File: dub.sdl
////
authors "Vijay Nayar"
description "A library of D source files generated from a proto file."
name "proto"
targetType "library"

dependency "protobuf" version="~>0.5.4"

// Because a library with no source files will fail to build, even before preBuild commands
// are run, a file `source/dummy.d` is created.  The time-stamp of this file is also used to
// determine if the `protoc` compiler needs to be run again.

// Use the protoc compiler to generate D source files from the data.proto file if it has changed.
preBuildCommands "cd $PACKAGE_DIR ; \
    test source/dummy.d -nt data.proto || \
    { \
      echo 'Generating D source files from data.proto.' ; \
      protoc $$PROTO_PATH --plugin=/usr/local/bin/protoc-gen-d --d_opt=message-as-struct \
          --d_out=source data.proto ; \
    }"

// Use the dummy file to also note the time the last build was run.
postBuildCommands "cd $PACKAGE_DIR ; touch source/dummy.d"
```

This approach works but has a number of flaws.  Firstly, it depends on having to know the exact path of the `protoc-gen-d` plugin which I have installed locally.  Additionally, all these commands are specific to the exact name of the proto file.

**Comment by denizzzka** [comment]
It is better to generate D files for access to Protobuf data manually, not by use `preBuildCommands`
Just generate it and then add obtained files to repository.

This is common usecase of protobuf usage with any language, not only with D.

**Comment by dcarp** [comment]
I think this would be more an issue for the dub project.
If you have some good idea how such an example should look like, I will be more than happy to integrate it.
