### ISSUE TITLE
Add support for proto2

### ISSUE THREAD

**Issue by ghost91-** [dcarp/protobuf-d#25]
proto2 is still quite common, so we should consider supporting it. E.g. the proto files I deal with at work are all proto2 files.

**Comment by dcarp** [comment]
`protoc2` is still common but not the scope of this project. Main differences are:
* handling of default values
* handling of unknown fields

Supporting those would complicate the implementation quite a lot.
The good part is that if one does not relay on those in `proto2`, then they can be migrated very easily to `proto3`

**Comment by ghost91-** [comment]
That's unfortunate to hear, but OK.

**Comment by denizzzka** [comment]
@ghost91(probably) you can read all proto2 binary data by using especially fromatted proto3 description.

For example, I sucessfully read OSM PBF data (which proto2) by protobuf-d package:
https://github.com/denizzzka/gis-stuff
