### ISSUE TITLE
descriptor.d is missing in src/google/protobuf

### ISSUE THREAD

**Issue by ghost91-** [dcarp/protobuf-d#26]

**Comment by dcarp** [comment]
`descriptor.d` is relevant for the protoc plugin. Please find the `protoc3` compatible version under `protoc_gen_d/google/protobuf/descriptor.d`

**Comment by ghost91-** [comment]
Yes, I found it there, but it is actually also relevant for user code. I have proto files which import it because they extend `FieldOptions` with custom options. The options are probably not actually relevant for the D code, but an import statement for `google.protobuf.descriptor` is generated, which then of course fails.

**Comment by dcarp** [comment]
`extend` was also removed in `proto3`. Does this will require `proto2` support anyway?

**Comment by ghost91-** [comment]
I suppose so. Feel free to close this then.
