### ISSUE TITLE
oneof setters behaviour

### ISSUE THREAD

**Issue by denizzzka** [dcarp/protobuf-d#27]
I wrote some .proto file and compiled it as structs:
```proto
syntax = "proto3";

package SomeProtocol;

message External
{
   oneof payload
   {
      Internal_msg1 i1 = 1;
      Internal_msg2 i2 = 2;
   }
}

message Internal_msg1
{
   bytes aaa = 1;
}

message Internal_msg2
{
   bytes aaa = 1;
}
```

Then I try to assign up `i1` message and test it:
```D
import SomeProtocol.descr;

void main()
{
    External ext;
    ext.i1.aaa = cast(byte[])[1, 2 ,3];

    assert(ext.payloadCase == External.PayloadCase.payloadNotSet); //not fail, but expected fail
    assert(ext.payloadCase == External.PayloadCase.i1); // fail
}
```

I.e., in this case `payloadCase` isn't set.

This is as designed behaviour? How to use `oneof` properly in this case?

**Comment by dcarp** [comment]
This does not call the setter, but the getter which, by design, returns the default value of the member type.
'ext.i1 = InternalMsg1(cast(bytes) [1, 2,3]);' should work as expected.

**Comment by denizzzka** [comment]
Thanks for clarify!

> This does not call the setter

That would be very convenient. Are there any chances to add such functionality or is it unrealistic?
