### ISSUE TITLE
please help to build prometheus protobuf files

### ISSUE THREAD

**Issue by ikod** [dcarp/protobuf-d#29]
Hello, @dcarp 

I can't build files for prometheus proto: https://github.com/prometheus/prometheus/blob/master/prompb/remote.proto

```
protoc -I./protobuf/protobuf -Iprotobuf -Iproto --plugin=/var/tmp/protobuf-d/build/protoc-gen-d --d_out=. proto/remote.proto
--d_out: Can only generate D code for proto3 .proto files.
Please add 'syntax = "proto3";' to the top of your .proto file.
```

And I can't find which file have no proto3 syntax

Thanks!

**Comment by dcarp** [comment]
master:latest contains a improved error message that should point to the file with the missing proto3 directive.
