### ISSUE TITLE
Generating googleapis client libraries with protobuf-d

### ISSUE THREAD

**Issue by Robert-Aron293** [dcarp/protobuf-d#30]
Hello!

I am currently working on "D Language Client Libraries for Google APIs" project[0][1].
The first step was to familiarize myself with protobuf and to generate client library for cloud/vision using python plugin with protoc.
Today I generated the same library with protobuf-d. When I tried to translate this example[2] from python to D, I noticed that some pieces of code are missing from the D generated library, for example the ImageAnnotatorClient class(or struct) (I could not found it anywhere in the generated code).

Here is the command that I used to generate the client library:

protoc path/to/cloud/vision/proto/files \
--proto_path=path/to/common/api/protos --proto-path=. \
--plugin=path/to/protobuf-d --d_opt=message-as-struct \
--d_out=path/to/output/files

Is that ok? Does it work as it should?

Thanks!

[0] https://github.com/dlang/projects/issues/66
[1]https://forum.dlang.org/post/eaefvlbgikujonfjjzqi@forum.dlang.org
[2] https://gapic-generator-python.readthedocs.io/en/stable/getting-started/docker.html#verifying-the-library

**Comment by dcarp** [comment]
Hi Robert,

this is expected. `ImageAnnotator` is a service. `protobuf-d` does not handle the RPC, which is implementation dependent, in your case gRPC.
`protobuf-d` can encode the parameters of the call and decode the result, but will not handle the call itself. For that you can use a library like: https://code.dlang.org/packages/grpc.
