### ISSUE TITLE
empty message error.

### ISSUE THREAD

**Issue by zhangyuchun** [dcarp/protobuf-d#9]
protobuf-0.3.1/protobuf/src/google/protobuf/common.d(147,5): Error: static assert:  "Definition of 'LeaseLeasesRequest' has no Proto field"

message LeaseLeasesRequest {
}

sometimes empty message is useful , for example used in grpc.

**Comment by zhangyuchun** [comment]
i‘m implementing neton like etcd. using empty message.
https://github.com/etcd-io/etcd/blob/master/etcdserver/etcdserverpb/rpc.proto

**Comment by dcarp** [comment]
Fixed in [v0.4.0](https://github.com/dcarp/protobuf-d/releases/tag/v0.4.0).

**Comment by dcarp** [comment]
Thank you for reporting this issue. Please test it and give feedback if this works for you now.

**Comment by zhangyuchun** [comment]
it works!
